import { Features } from "../components/Features";
import { ImageCTA } from "../stories/ImageCTA";
import { Config } from "../util/config";
import Head from "next/head";

import { features, featuredProducts, events } from "../util/data";
import { WCard } from "@/components/WCard";
import { Card } from "@/components/Card";
import { CardContainer } from "@/components/CardContainer";
import { Section } from "@/components/Section";
import { CTANewsletter } from "@/components/CTANewsletter";
import { CTAHeading } from "@/components/CTAHeading";

export default function Home() {
  return (
    <>
      <Head>
        <title>{Config.site.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <ImageCTA heading="Cannabis In Living Color" ctaBtnLabel="Learn More" />
        <Section title="Features and Benefits">
          <Features data={features} />
        </Section>
        <Section
          title="Coming Soon / What's Happening Now / Happenings"
          fullWidth
        >
          <CardContainer data={featuredProducts} />
        </Section>
        <ImageCTA heading="Featured Product" ctaBtnLabel="Learn More" />
        <ImageCTA
          heading="Another Featured Product or Category"
          left
          ctaBtnLabel="Learn More"
        />
        <CTAHeading title="Your Field Guide to Cannabis In New Mexico" />
        <CTANewsletter />
        <CTAHeading title="Our Story" />
      </main>
    </>
  );
}
