import { Features } from "../components/Features";
import { ImageCTA } from "../stories/ImageCTA";
import { Config } from "../util/config";
import Head from "next/head";

import { features, featuredProducts, events } from "../util/data";
import { WCard } from "@/components/WCard";
import { Card } from "@/components/Card";
import { CardContainer } from "@/components/CardContainer";
import { Section } from "@/components/Section";
import { CTANewsletter } from "@/components/CTANewsletter";
import { CTAHeading } from "@/components/CTAHeading";

export default function Home() {
  return (
    <>
      <Head>
        <title>{Config.site.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <ImageCTA heading="This is a Hero Heading" />
        <Section title="Features and Benefits">
          <Features data={features} />
        </Section>
        <Section title="Featured Products" fullWidth>
          <CardContainer data={featuredProducts} />
        </Section>
        <ImageCTA heading="Featured Product" />
        <CTAHeading title="Education / Learn CTA Section" />
        <CTANewsletter />
        <CTAHeading title="Our Story" />
        <Section title="Events" fullWidth>
          <CardContainer data={events} />
        </Section>
      </main>
    </>
  );
}
